# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_weblink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weblink',
            options={'ordering': ['title', 'web_url']},
        ),
        migrations.AddField(
            model_name='weblink',
            name='web_url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
