# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161107_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('staff_size', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('fiscal_year', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0, max_length=40)),
                ('start_date', models.DateField(blank=True)),
                ('close_date', models.DateField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.Department')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
