# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161109_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='projects',
        ),
        migrations.AddField(
            model_name='contact',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Project'),
        ),
    ]
