# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161110_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='projects',
            field=models.ManyToManyField(blank=True, to='blog.Project'),
        ),
    ]
